version: '2'
services:
    caesgatos-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/CaesGatos/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=CaesGatos
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
